//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTreinamentoG160.DataApplicator.Logic.Northwind
{
    
    using System; 
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using SGI.Common.DataApplicator;
    using ProjetoTreinamentoG160.ModelData.Logic.Northwind.Model;
    /// <summary>
    /// EmployeesDataApplicator class DataApplicator
    /// </summary>
    public class EmployeesDataApplicator : WinDataApplicatorEF<NorthwindEntities, Employees>
    {
    
    	public EmployeesDataApplicator(NorthwindEntities contexto)
    	    : base(contexto)
    	{
    	}
    
    }
}
