//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTreinamentoG160.Business.Logic.Northwind
{
    
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.ComponentModel;
    using SGI.Common.BusinessContractor.Rules;
    using SGI.Common.BusinessContractor.Base;
    using ProjetoTreinamentoG160.ModelData.Logic.Northwind.Model;
    
    /// <summary>
    /// RV_EmployeesBusiness class Business
    /// </summary>
    [RegraAtiva(true)]
    public class RV_EmployeesBusiness : GenericRuleEF<NorthwindEntities , Employees>
    {
    
    	public RV_EmployeesBusiness(NorthwindEntities contexto, Employees instancia)
            : base(contexto, instancia)
       	    {
            }
    
            /// <summary>
            /// Executa a validação da regra
            /// </summary>
            public override bool Consistir()
            {
                try
                {
                if (instancia.FirstName.Length == 0)
                {
                    Mensagens.Add(new RulesMessage(000, "RV_EmployeesBusiness", "O campo não pode ser nulo"));
                }
                if (instancia.FirstName.Length < 5)
                {
                    Mensagens.Add(new RulesMessage(000, "RV_EmployeesBusiness", "O campo tem que ser maior que 5 caracteres"));
                    return false;
                }
                if (instancia.LastName.Length == 0)
                {
                    Mensagens.Add(new RulesMessage(000, "RV_EmployeesBusiness", "O campo não pode ser nulo"));
                }
                if (instancia.LastName.Length < 5)
                {
                    Mensagens.Add(new RulesMessage(000, "RV_Modelo_Business", "O campo deve conter mais que 5 caracteres"));
                    return false;
                }

                return true;
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
    
    }
}
