//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTreinamentoG160.ModelData.Logic.Northwind.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using ProjetoTreinamentoG160.ModelData.Logic.Northwind.MetaData;
    
    [Serializable]
    [MetadataType(typeof(CategoriesMetaData))]
    
    public partial class Categories
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	public Categories()
    	{
    		this.Products = new HashSet<Products>();
    	}
    
    	public int CategoryID { get; set; }
    	public string CategoryName { get; set; }
    	public string Description { get; set; }
    	public byte[] Picture { get; set; }
    
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	public virtual ICollection<Products> Products { get; set; }
    }
}
