//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTreinamentoG160.ModelData.Logic.Northwind.Model
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using ProjetoTreinamentoG160.ModelData.Logic.Northwind.MetaData;
    
    [Serializable]
    [MetadataType(typeof(CustomerDemographicsMetaData))]
    
    public partial class CustomerDemographics
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	public CustomerDemographics()
    	{
    		this.Customers = new HashSet<Customers>();
    	}
    
    	public string CustomerTypeID { get; set; }
    	public string CustomerDesc { get; set; }
    
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	public virtual ICollection<Customers> Customers { get; set; }
    }
}
